universities = {'American International College':['Springfield','Private not-for-profit','Masters university',2177,1885],
 'Amherst College':['Amherst','Private not-for-profit','Baccalaureate college',1817,1821],
 'Andover Newton Theological School':['Newton','Private not-for-profit','Special-focus institution',273,1965],
 'Anna Maria College':['Paxton','Private not-for-profit','Masters university',1455,1946],
 'Assumption College':['Worcester','Private not-for-profit','Masters university',2813,1904],
 'Atlantic Union College':['South Lancaster','Private not-for-profit',None,None,1882],
 'Babson College':['Wellesley','Private not-for-profit','Special-focus institution',3250,1919],
 'Bard College at Simons Rock':['Great Barrington','Private not-for-profit','Baccalaureate/associates college',354,1964],
 'Bay Path University':['Longmeadow','Private not-for-profit','Baccalaureate college',2370,1897],
 'Bay State College':['Boston','For-profit','Associates college',1721,1946],
 'Becker College':['Worcester','Private not-for-profit','Baccalaureate college',1826,1784],
 'Benjamin Franklin Institute of Technology':['Boston','Private not-for-profit','Special-focus institution',475,1908],
 'Bentley University':['Waltham','Private not-for-profit','Masters university',5647,1917],
 'Berklee College of Music':['Boston','Private not-for-profit','Special-focus institution',4255,1945],
 'Berkshire Community College':['Pittsfield','Public','Associates college',2503,1960],
 'Pope St. John XXIII National Seminary':['Weston','Private not-for-profit','Special-focus institution',66,1964],
 'Boston Architectural College':['Boston','Private not-for-profit','Special-focus institution',941,1889],
 'Boston Baptist College':['Milton','Private not-for-profit','Special-focus institution',89,1976],
 'Boston College':['Chestnut Hill','Private not-for-profit','Research university',14605,1863],
 'Boston Graduate School of Psychoanalysis':['Brookline','Private not-for-profit','Special-focus institution',165,1973],
 'Boston University':['Boston','Private not-for-profit','Research university',32603,1839],
 'Brandeis University':['Waltham','Private not-for-profit','Research university',5808,1948],
 'Bridgewater State University':['Bridgewater','Public','Masters university',11417,1840],
 'Bristol Community College':['Fall River','Public','Associates college',9022,1965],
 'Bunker Hill Community College':['Boston','Public','Associates college',13504,1973],	
 'Cambridge College':['Cambridge','Private not-for-profit','Masters university',3378,1971], 	
 'Cape Cod Community College':['West Barnstable','Public','Associates college',4201,1961],	
 'Clark University':['Worcester','Private not-for-profit','Research university',3210,1887],
 'College of the Holy Cross':['Worcester','Private not-for-profit','Baccalaureate college',2926,1843],
 'Conway School of Landscape Design':['Conway','Private not-for-profit','Special-focus institution',18,1972],
 'Curry College':['Milton','Private not-for-profit','Masters university',3097,1879],
 'Dean College':['Franklin','Private not-for-profit','Associates college',1322,1865],
 'Eastern Nazarene College':['Quincy','Private not-for-profit','Baccalaureate college',1459,1900],
 'Elms College':['Chicopee','Private not-for-profit','Baccalaureate college',1576,1928],
 'Emerson College':['Boston','Private not-for-profit','Masters university',4531,1880],
 'Emmanuel College':['Boston','Private not-for-profit','Masters university',2489,1919],
 'Endicott College':['Beverly','Private not-for-profit','Masters university',4408,1939],
 'Fisher College':['Boston','Private not-for-profit','Baccalaureate college',2037,1903],
 'Fitchburg State University':['Fitchburg','Public','Masters university',6889,1894],
 'Framingham State University':['Framingham','Public','Masters university',6506,1839],
 'Franklin W. Olin College of Engineering':['Needham','Private not-for-profit','Special-focus institution',355,1997],
 'Gordon College':['Wenham','Private not-for-profit','Baccalaureate college',1906,1889],
 'Gordon Conwell Theological Seminary':['South Hamilton','Private not-for-profit','Special-focus institution',2033,1969], 
 'Greenfield Community College':['Greenfield','Public','Associates college',2437,1962],
 'Hallmark Institute of Photography':['Turners Falls','For-profit','Special-focus institution',72,1975],
 'Hampshire College':['Amherst','Private not-for-profit','Baccalaureate college',1461,1970],
 'Harvard University':['Cambridge','Private not-for-profit','Research university',28147,1636], 	
 'Hebrew College':['Newton','Private not-for-profit','Special-focus institution',231,1921],
 'Hellenic College Holy Cross Greek Orthodox School of Theology':['Brookline','Private not-for-profit','Special-focus institution',209,1937],
 'Holyoke Community College':['Holyoke','Public','Associates college',7164,1946],
 'Hult International Business School':['Cambridge','Private not-for-profit','Special-focus institution',2648,1964],
 'Laboure College':['Boston','Private not-for-profit','Associates college',727,1892],
 'Lasell College':['Newton','Private not-for-profit','Baccalaureate college',1980,1851],
 'Lesley University':['Cambridge','Private not-for-profit','Masters university',5944,1909],
 'Longy School of Music of Bard College':['Cambridge','Private not-for-profit','Special-focus institution',224,1915],
 'Massachusetts Bay Community College':['Wellesley','Public','Associates college',5427,1961],
 'Massachusetts College of Art and Design':['Boston','Public','Special-focus institution',2326,1873],
 'Massachusetts College of Liberal Arts':['North Adams','Public','Baccalaureate college',1799,1894],
 'Massachusetts Institute of Technology':['Cambridge','Private not-for-profit','Research university',11189,1861],
 'Massachusetts Maritime Academy':['Bourne','Public','Baccalaureate college',1135,1891],
 'Massachusetts School of Law':['Andover','Private not-for-profit','Special-focus institution',580,1988],
 'Massasoit Community College':['Brockton','Public','Associates college',8209,1966],
 'MCPHS University':['Boston','Private not-for-profit','Special-focus institution',6010,1823],
 'Merrimack College':['North Andover','Private not-for-profit','Baccalaureate college',2694,1947],
 'MGH Institute of Health Professions':['Boston','Private not-for-profit','Baccalaureate college',1036,1977],
 'Middlesex Community College':[['Lowell', 'Bedford'],'Public','Associates college',9664,1970],
 'Montserrat College of Art':['Beverly','Private not-for-profit','Special-focus institution',396,1970],
 'Mount Holyoke College':['South Hadley','Private not-for-profit','Baccalaureate college',2347,1837],
 'Mount Ida College':['Newton','Private not-for-profit','Baccalaureate college',1389,1899],
 'Mount Wachusett Community College':['Gardner','Public','Associates college',4731,1963],
 'New England College of Optometry':['Boston','Private not-for-profit','Special-focus institution',502,1894],
 'New England Conservatory of Music':['Boston','Private not-for-profit','Special-focus institution',813,1867],
 'New England School of Law':['Boston','Private not-for-profit','Special-focus institution',964,1938],
 'New England School of Photography':['Boston','For-profit','Special-focus institution',66,1968],
 'Newbury College':['Brookline','Private not-for-profit','Baccalaureate college',751,1962],
 'Nichols College':['Dudley','Private not-for-profit','Special-focus institution',1459,1815],
 'North Shore Community College':['Danvers','Public','Associates college',7750,1965],
 'Northeastern University':['Boston','Private not-for-profit','Research university',20053,1898],
 'Northern Essex Community College':['Haverhill','Public','Associates college',7352,1972],
 'Northpoint Bible College':['Haverhill','Private not-for-profit','Special-focus institution',472,1924],
 'Pine Manor College':['Chestnut Hill','Private not-for-profit','Baccalaureate college',346,1911],
 'Quincy College':['Quincy','Public','Associates college',4576,1958],
 'Quinsigamond Community College':['Worcester','Public','Associates college',8582,1963],
 'Regis College':['Weston','Private not-for-profit','Masters university',2069,1927],
 'Roxbury Community College':['Roxbury','Public','Associates college',2437,1973],
 'Saint Johns Seminary':['Brighton','Private not-for-profit','Special-focus institution',192,1884],
 'Salem State University':['Salem','Public','Masters university',10085,1854],
 'School of the Museum of Fine Arts':['Boston','Private not-for-profit','Special-focus institution',651,1876],
 'Simmons College':['Boston','Private not-for-profit','Masters university',4655,1899],
 'Smith College':['Northampton','Private not-for-profit','Baccalaureate college',3033,1875],
 'Springfield College (Massachusetts)':['Springfield','Private not-for-profit','Masters university',5018,1885],
 'Springfield Technical Community College':['Springfield','Public','Associates college',6792,1967],
 'Stonehill College':['Easton','Private not-for-profit','Baccalaureate college',2481,1948],
 'Suffolk University':['Boston','Private not-for-profit','Research university',8675,1906],
 'Tufts University':['Medford','Private not-for-profit','Research university',10872,1852],
 'University of Massachusetts Amherst':['Amherst','Public','Research university',28518,1863],
 'University of Massachusetts Boston':['Boston','Public','Research university',16277,1964],	
 'University of Massachusetts Dartmouth':['Dartmouth','Public','Masters university',9053,1962],
 'University of Massachusetts Lowell':['Lowell','Public','Research university',16932,1894],
 'University of Massachusetts Medical School':['Worcester','Public','Special-focus institution',1161,1962],
 'Urban College of Boston':['Boston','Private not-for-profit','Associates college',762,1993],
 'Wellesley College':['Wellesley','Private not-for-profit','Baccalaureate college',2474,1875],
 'Wentworth Institute of Technology':['Boston','Private not-for-profit','Special-focus institution',4179,1904],
 'Western New England University':['Springfield','Private not-for-profit','Masters university',3657,1919],
 'Westfield State University':['Westfield','Public','Masters university',6371,1838],
 'Wheaton College':['Norton','Private not-for-profit','Baccalaureate college',1654,1834],
 'Wheelock College':['Boston','Private not-for-profit','Masters university',1378,1939],
 'William James College':['Boston','Private not-for-profit','Special-focus institution',650,1974],
 'Williams College':['Williamstown','Private not-for-profit','Baccalaureate college',2150,1793],
 'Worcester Polytechnic Institute':['Worcester','Private not-for-profit','Research university',6296,1865],
 'Worcester State University':['Worcester','Public','Masters university',6447,1874]}

for uni in universities:
 print(uni)
